kubectl create secret generic rds-secret \
  --from-literal=DB_HOST=<database-endpoint> \
  --from-literal=DB_USER=<databse-username> \
  --from-literal=DB_PASSWORD=<database-password> \
  --from-literal=DB_NAME=<database name>