apiVersion: v1
kind: Service
metadata:
  name: node-mysql-service
spec:
  type: NodePort   # use LoadBalancer in cloud (EKS)
  selector:
    app: node-mysql
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30007